---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64 
      box_url: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[brct::default]
      - recipe[brct::metadata]
    attributes:
      bundler:
        version: '1.12.5'       
