name 'brct'
maintainer 'Cândido Sales Gomes'
maintainer_email 'candido.sales@brasilct.com'
license 'all_rights'
description 'Installs/Configures brct'
long_description 'Installs/Configures brct'
version '0.1.0'
