name 'brct'
maintainer 'Cândido Sales Gomes'
maintainer_email 'candido.sales@brasilct.com'
license 'all_rights'
description 'Installs/Configures brct'
long_description 'Installs/Configures brct'
version '1.0.0'

depends 'nodejs', '~> 2.4.4'
depends 'rbenv', '~> 1.7.1'