---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64 
      box_url: ubuntu/xenial64

suites:
  - name: default
    run_list:
    attributes:
